name: Build and Deploy to GitHub Pages

# Trigger on pushes to main
on:
  push:
    branches:
      - main

# Ensure the workflow can push to gh-pages
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the project
      - name: Build project
        run: npm run build

      # 5️⃣ Optional: Force redeploy even if files didn't change
      - name: Force redeploy
        run: |
          echo "redeploy $(date)" > .redeploy
          git add .redeploy
          git commit -m "Force Pages redeploy" || echo "No changes to commit"

      # 6️⃣ Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
