name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write  # needed for Actions to push

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the project
      - name: Build project
        run: npm run build

      # 5️⃣ Force redeploy (optional, ensures Pages rebuild)
      - name: Force redeploy
        run: |
          echo "redeploy $(date)" > .redeploy
          git add .redeploy
          git commit -m "Force Pages redeploy" || echo "No changes to commit"

      # 6️⃣ Deploy to gh-pages branch (contents of dist go to root)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist        # push contents of dist to root
          force_orphan: true         # ensures a fresh commit each time
